# Range selection

Resolve a human request against TASKS and any active FEATURE-TASKS before implementation starts. For an explicit feature request, select from FEATURE-TASKS and check external prerequisites in TASKS; for an explicit main-project request, use TASKS. If both contain eligible work and an unqualified “next” has no clear active scope, report the ambiguity instead of mixing the lists or choosing silently. Read the relevant PLAN or FEATURE-PLAN exits, dependency notes, and the current Git and worktree evidence from orientation. A checked item in either list alone does not establish completion; review task evidence if status is disputed or stale, obtaining **sdd-tasks** progress review when needed, and route feature-delta reconciliation to **sdd-integrate-feature**; direct checkpoint amendments require a human command to **sdd-steer**. Resolve interrupted or ambiguous task state using the **sdd-orient** handoff before selecting new work.

Inspect **Completion reassessment pending** notes in owning entries or linked evidence. Treat affected checked tasks and parents as disputed, assess their current acceptance and dependency consequences, and include in-scope reassessment in the requested range rather than skipping it because every box is checked. Report an out-of-range reassessment as a scope conflict. Selection-only reports these facts without running checks, correcting status, or clearing notes.

1. Identify the applicable task list and requested unit: one named task, the next eligible task, the next N eligible tasks, a named milestone, the next milestone, a named phase, or the next phase. Count explicit milestone/phase review/report tasks as tasks too; do not skip them or append out-of-range review work. Count **tasks** only for “N tasks”; count phase or milestone units only when the request names that unit. Resolve “next” from verified completion and dependency order, not from the first unchecked box alone.
2. Expand the request to precise task IDs and enclosing milestone or phase. Use globally unique IDs for dependencies across lists; check prerequisites and identify any blocked or out-of-range dependency. Do not silently expand the authorized range; report the dependency and obtain its resolution through the appropriate workflow.
3. State the selected IDs, prerequisite evidence, expected end condition, and the stopping boundary. An implementation agent must stop at that boundary for human review, even if subsequent tasks are ready. If no eligible work remains, report why without inventing work.

A selection-only request is read-only and stops after reporting the range. It does not enter the push-first execution protocol. Selection within an implementation request follows startup pushing and interrupted-task handling. It does not mark tasks done, run checks, create a commit, or authorize the implementation workflow. A user may explicitly select a different valid order; document the dependency consequences instead of silently replacing their range.

## Phase branch segments

For main TASKS, identify the owning phase of each selected task and its full exit obligations. Execute a partial range on that phase branch and stop after persistence without integrating an unfinished phase. Split an authorized range spanning phases into sequential phase segments; complete/verify/publish each phase before starting the next branch. If the request excludes remaining work or evidence needed for the phase exit, report the blocker or pause rather than expanding the selected IDs. Selection-only identifies these boundaries without branch changes.
