# Review milestone and phase implementation

For explicit milestone/phase review tasks, assess code as well as running checks. Apply the shared [backend object lifecycle](../../sdd-conventions/references/backend-object-lifecycle.md). Establish exact source/commits, owning tasks, accepted SPEC/PLAN exits and report destination. This review is read-only: return repairs to sdd-implement (or sdd-steer for its authorized amendment), test changes to sdd-tdd, and documentation maintenance to sdd-docs.

1. Inspect the delivered implementation and relevant dependencies as a coherent capability, not just task checkboxes or the last diff. Assess contract adherence, interfaces/data flow, error/resource handling, integration and failure paths, maintainability and tests/documentation relevant to those contracts. Apply sdd-conventions modularity/design criteria where useful. Route specialist design/contract concerns through sdd-manage without silently changing requirements.
2. For a milestone, cover all constituent delivery work and its exits. For a phase, cover cross-milestone interactions, regressions, phase-wide exits and remaining milestone findings after delivery milestones close. Prior milestone reviews do not waive phase review.
3. Record located findings with stable IDs, severity/impact, objective evidence and repair/recheck recommendations. Bugs, critical code issues, SPEC/PLAN violations and missing required evidence block completion. Only non-critical code issues consistent with contracts/exits may be proposed for deferral, with rationale and solution options/tradeoffs.
4. Select/run checks using the existing verification references. Record actual commands/results, condition coverage and limits separately from code inspection. Return rechecks after repairs; do not infer a successful review from passing tests alone.
5. Supply sdd-report with exact reviewed state, coverage, findings/rechecks, exits, unresolved TODO provenance and proposed disposition. Return completion blockers to the execution owner. The report's persistence and task/issue/milestone completion remain execution/backend responsibilities.

Retain valid earlier review evidence on continuation. If implementation changed after review, recheck affected findings and dependent scope against the new source. A partially written report or lost check response is not proof that review/testing finished. No mandatory second review journal or separate review campaign is needed for an ordinary boundary task.
