---
name: sdd-integrate-feature
description: Use when incorporating accepted feature or change documents into the main PROJECT, ARCHITECTURE, DECOMPOSITION, SPEC, PLAN, or layout documents, or reconciling TASKS and FEATURE-TASKS from accepted feature deltas, including optional incorporation of FEATURE-TASKS into TASKS. Reconcile one selected document or a bounded set without requiring task-list changes.
---

# Integrate an accepted feature

Read [feature incorporation](references/feature-incorporation.md) for the scoped reconciliation procedure. This skill owns incorporation of accepted feature deltas into main project documents and reconciliation of TASKS and FEATURE-TASKS within the requested scope, including feature-related task and dependency revisions and feature-list incorporation into TASKS. Direct human-commanded checkpoint amendments belong to **sdd-steer**, which updates existing documents without this integration step. A request to reconcile one document does not authorize edits to the others. Review without mutation remains with the relevant focused skill.

Identify the requested target set before editing: PROJECT, ARCHITECTURE and its children, DECOMPOSITION and its children, SPEC and its children, PLAN and its children, layout and its children, TASKS, or FEATURE-TASKS. Reconcile any subset whose accepted source delta and main owner are established. Include TASKS or FEATURE-TASKS only when task-list reconciliation is requested or explicitly included in the coordinated scope. Transferring task ownership into TASKS requires both TASKS and FEATURE-TASKS in the edit scope so each task retains exactly one executable entry. TASKS-only reconciliation may revise existing main entries but does not copy active feature tasks. A document-only reconciliation can leave FEATURE-TASKS active; report its affected links or assumptions for later work.

Before mutation, **sdd-manage** coordinates the user's requested scope and a current **sdd-orient** handoff establishing an eligible Git worktree, applicable instructions, target paths, and ownership of dirty changes. Use **sdd-manage**'s **Branch management** reference to establish or reuse the selected integration branch and target; within an active feature campaign, reconcile on its existing working branch. Inspect accepted feature sources, main owners, and relevant dependents. Resolve conflicts or missing decisions with their owning workflow rather than guessing. Use **sdd-conventions** for affected document and component boundaries. This skill does not authorize implementation, task execution, hosted mutations, or automatic progression to other stages.

Return the main documents incorporated, feature sources active or historically archived, dependency impacts outside the selected scope, unresolved conflicts, and task-list status. Distinguish document incorporation from implementation or verified task completion.

For interrupted incorporation, load the continuation section of [feature incorporation](references/feature-incorporation.md). Inspect actual selected documents against the established checkpoint and accepted sources; resume the same scoped reconciliation without assuming that dirty files represent interrupted task implementation. Return coherent document differences and unresolved reassessment to the coordinator for verification, persistence, and default explicit Git integration. This skill owns document incorporation, not the Git merge.
