# Task-list conformance and decomposition review

Use after TASKS/FEATURE-TASKS generation or material amendment, and for an explicit structure/conformance review. [Progress review](progress-review.md) instead assesses completion evidence; it cannot substitute for preparation QC. Apply **sdd-conventions**' **Development-document QC**, **Task hierarchy** and **Backend object lifecycle** references.

## Inputs and review

1. Identify selected owning list/children, exact state, accepted design/SPEC/PLAN/layout and current upstream review evidence. For a feature, review the delta against accepted main/feature sources without forcing unselected whole-project edits. A missing FEATURE-PLAN is acceptable only when sufficient accepted main strategy supplies its boundaries. Absent/stale required PLAN conformance blocks task derivation/use; coordinate the focused review rather than inventing a pass.
2. Map each planned delivery outcome and exit to sufficient executable work and trace acceptance to SPEC using existing IDs/links. Assess missing/duplicated scope, invented behavior, hidden strategy changes, feasible dependencies and implementation/test/documentation/failure/integration/packaging coverage. Preserve PLAN phase/milestone IDs and accepted boundaries.
3. Report delivery task counts for every delivery milestone and separately identify excluded dedicated review/report-only tasks. Apply shared 3–5 guidance and explicit 1–2/10+ assessments with rationale; inspect semantic size even for in-range groups. Do not count a task's own checks/docs as extra tasks, hide whole subsystems behind a single ID, or split into trivial edits to meet a number. Empty delivery groups require correction or accepted purpose. The mandatory one-task phase review milestone is excluded from this diagnostic, never from execution selection.
4. Check project-wide unique stable task IDs, exactly one executable owner, four-space checklist hierarchy, prerequisite feasibility, explicit final review/testing/report task per delivery milestone and final one-task phase review milestone. Review links and report paths against lifecycle policy. Checked status requires separate progress evidence; this review does not mark implementation complete.

## Corrections, evidence and gate

Authoring includes bounded initial task-list corrections, recheck and adjacent `TASKS-REVIEW-REPORT.md` or `FEATURE-TASKS-REVIEW-REPORT.md` through **sdd-report**'s **Document QC reports** format. The root report covers applicable children. Preserve original located findings and append Revision N cycles; count rationale is an assessment, not an automatic defect.

A task breakdown that exposes inadequate PLAN returns an amendment to sdd-plan, then rechecks affected inputs; do not silently change delivery strategy in TASKS. Necessary SPEC/design decisions return to their owners. Existing feature reconciliation belongs to sdd-integrate-feature; commanded checkpoint amendments belong to sdd-steer. Review-only returns findings without changing the governing list, checkboxes or code. A report is written only within authorized scope.

Correct all confirmed QC/conformance issues before implementation or hosted projection. Persist corrected list and report together through sdd-manage, then hand current Ready evidence to dependents. A known deferred issue or stale report remains Blocked; explicit human exceptions record scope/consequences without declaring a pass. Pure selection may identify candidate IDs but must report blocked execution eligibility. On interruption compare actual files, pending corrections, source identities and Git evidence before continuing the same review; preserve valid work and append rather than duplicate history.
