# GitHub milestone lifecycle

Use the shared [backend object lifecycle](../../sdd-conventions/references/backend-object-lifecycle.md) and [GitHub backend](github.md) access, ownership and uncertain-write rules. sdd-implement requests verified boundary reconciliation; sdd-manage coordinates authorization. This backend never runs reviews, changes task status or creates Git commits.

## Resolve and close

1. Resolve repository, stable phase/milestone ID and actual owning TASKS plus active FEATURE-TASKS. Inspect the accepted PLAN exits and committed report/evidence supplied by execution. Enumerate open and closed milestones with complete pagination; match the exact stable ID using the projection naming convention, validate name/description/parent scope, and stop on conflicting or multiple matches. Renamed titles do not authorize a duplicate. If identity cannot be established, report the conflict.
2. Resolve every constituent task's unique issue using the exact title/body marker protocol, including the review/report task. Check all owning lists for work belonging to this project milestone; a feature parent alone is insufficient. Read every issue associated with the milestone, including closed states and complete pagination; distinguish pull requests. Unexpected open foreign issues or PRs and conflicting ownership block closure. Preserve them and return the needed disposition.
3. Require verified local task acceptance, committed/pushed milestone report, applicable review/tests/exits and closed task issues with matching completion evidence. For a phase review milestone, its sole task supplies the phase report, and preceding delivery milestones must already be closed. A closed issue or empty milestone alone cannot satisfy the gate. If expected work is cancelled/retired, require an explicitly accepted scope disposition instead of treating cancellation as verification.
4. If the milestone is already closed, validate its current evidence and report matched state without rewriting it. Otherwise use the [milestone update endpoint](https://docs.github.com/en/rest/issues/milestones#update-a-milestone) to request state `closed`, then read back the exact object. Return ID, number/URL, observed state and report/commit associations. Do not declare successful closure from an unobserved response or a local parent checkbox.

Task evidence comments follow [issue lifecycle](github-issue-lifecycle.md). A milestone report and its task commit establish evidence; no duplicate milestone journal or artificial evidence issue is required. GitHub phase labels remain after completion and are not closed/deleted.

## Reopen and recover

When an accepted amendment invalidates current milestone acceptance, reopen the uniquely resolved managed milestone under authorized reconciliation; preserve its earlier reports, closure history and unaffected issue states. Reopen affected task issues only when their current acceptance is invalidated, not merely because the milestone reopened. If a milestone was closed without adequate evidence, report the discrepancy and reconcile only within the authorized maintained scope.

After timeout, interruption or unavailable readback, retain closure/reopening outcome unknown. Re-read exact milestone state and associated issues/evidence before replay. Reuse confirmed completed effects; apply only remaining differences. Missing access, incomplete pagination, duplicate matches or contradictory evidence blocks replay and dependent phase transitions. On restored access, reconcile older pending milestones as well as current task issues using existing lists/reports/Git evidence. Preserve independent successful results and return pending/unknown operations and blockers.
