# Completion and checkpoints

## Complete and commit each task

1. Confirm the intended implementation, relevant tests and documentation, and task-specific verification are complete. Missing or contradictory required evidence blocks completion; a checkbox or green command alone is insufficient.
2. Mark the task complete in its owning TASKS or FEATURE-TASKS. Honor designated project evidence locations; otherwise record concise commands, observed outcomes, condition coverage, relevant state/limitations, and any authorized test-first exception alongside the task or in its existing linked evidence location. Clear its **Completion reassessment pending** note only when current acceptance is established, preserving earlier evidence as historical. Unresolved reassessment retains its note and cannot support a completed claim. Commit identity can be located by the task ID; do not require embedding a commit's own SHA in its content or adding a transaction journal.
3. Resolve hosted issue references through **sdd-forge** when tracking is active. Use **sdd-report** to compose a message with the task ID and verified issue associations, including closing keywords when the commit fully resolves an issue. Never guess an issue number. If hosting is unavailable, proceed with the local task commit and report unresolved references and closure as pending; preserve any associations already verified.
4. Apply **sdd-manage**'s [repository bootstrap](../../sdd-manage/references/repository-bootstrap.md) before the first SDD commit (after startup pushing); include its owned disclosure, usage notice and README links with the task result. Inspect the final diff and stage only task-owned result, test, documentation, status, and evidence changes. Preserve unrelated staged and unstaged content; do not include it through a blanket staging command. Inspect the staged diff and explicitly exclude unrelated staged content from the commit while preserving its index state. A normal commit includes everything staged, even when only task paths were newly added. Use a path-scoped commit only when the entire selected file content is task-owned, or isolate the selected changes in a temporary index. If task changes cannot be separated safely, report the conflict before committing.
5. Commit the result and completion status together. Confirm the resulting commit contents and remaining staged and unstaged diffs. After a temporary-index commit, ensure the ordinary index does not stage a reversal of the committed owned change; reconcile only its owned entries while preserving unrelated staged content. A checked but uncommitted task is completed pending work, not yet a durable completed task.
6. Push the task commit and all other outstanding commits on the current branch to the established remote branch. Assume existing shell authentication and attempt the push; on a 403 or explicit credential failure, coordinate recovery/retry through **sdd-manage**'s **Hosting credentials** protocol. Verify remote containment. Complete this push before implementing the next task. If it fails, preserve the commit and report the pending push rather than advancing.
7. For active hosted tracking, use **sdd-forge** to close the verified, committed task issue with the task ID, commit, and verification evidence. Reconcile existing closure without duplicate writes. On successful hosted access, also reconcile older pending references and closures for verified completed tasks within the established maintained tracking scope; do not inspect only the latest task. Derive this backlog from owning lists, Git evidence, and hosted state without adding a journal. If hosting is unavailable, retain local completion and report closure as pending; never equate hosting failure with implementation failure.

Provide a concise task result through **sdd-report** before advancing within the authorized range. The commit's task ID, checklist, and evidence establish the boundary for startup inspection if execution is interrupted.

## Execute review/report tasks

Apply the [backend object lifecycle](../../sdd-conventions/references/backend-object-lifecycle.md). Execute milestone/phase review tasks as explicit selected tasks; do not skip them or append unselected tasks to satisfy a requested count. Use sdd-verify for read-only code review and check evidence, sdd-tdd/sdd-docs for their focused changes, and sdd-report for the committed boundary report. Repair bugs, critical issues and contract violations before review task completion. Include admissible non-critical TODO findings with options/provenance; the final phase review includes the final implementation report when the full list completes. A report draft without completed review/tests is incomplete task work.

After the review task's result/report/status is committed, pushed and its issue closed, request sdd-forge milestone closure/readback. A phase review waits for every delivery milestone closure; its final milestone closes after its own review task. Retain pending closures on backend failure; do not infer synchronization from local checkboxes or advance to dependent phase gates. Local-only mode applies the same evidence gates without hosted objects.

## Parent completion and stopping

- Check a milestone only when its constituent tasks, required review/report and applicable PLAN exit conditions are verified; check a phase only when its milestones and phase exit conditions are verified. Empty or blocked groups are not complete by default.
- Reassess flagged parent claims against their current exit conditions; correct unsupported checked status and retain the pending note until those conditions are established. A resolved task reassessment alone does not clear its parent's note.
- In FEATURE-TASKS, a parent checkbox covers only that list's scoped work and relevant FEATURE-PLAN exits. It does not check the corresponding whole-project milestone or phase in TASKS.
- Commit and push parent status and any additional boundary evidence with the final task when available, or in a focused follow-up commit identifying the relevant task and parent boundary. Do not invent a new task solely to record parent status; explicit review/report tasks are already required by accepted PLAN/TASKS. Hosted closure remains a separately observed state, not authority for local acceptance.
- Do not start tasks beyond the requested task count, milestone, phase, or named checkpoint, even if further tasks are ready. Integrate only when the workflow gate is met; a completed main task subset in an incomplete phase pushes and pauses without a merge. Also stop for an unresolved implementation or push blocker or the user's pause instruction.
- Report implemented capabilities, completed IDs, acceptance and exit-condition evidence, unresolved failures or limitations, commit and push state, pending issue reconciliation, and remaining tasks. Distinguish task/working-branch completion from integration into the established target and its remote publication.

After the requested stopping boundary, the human decides whether to resume the main task list or command **sdd-steer** for a focused amendment. Do not start either automatically after the selected checkpoint.

## Integrate the completed boundary

Use **sdd-manage**'s **Git workflows** reference after the selected tasks and applicable exits are verified, committed, and pushed. Task persistence remains per task. For main development, merge once for a complete verified phase; a smaller requested range pushes and pauses on its phase branch. For a feature/revision, integrate only its coherent authorized boundary. Verify the entire prospective branch difference before integrating: an existing branch containing unrelated or unfinished work is a scope conflict. A pause or blocker returns branch state without a partial merge.

For a complete feature implementation request, coordinate incorporation of the accepted feature documents and task ownership required for its final main-document consistency through **sdd-integrate-feature**, on the working branch before final verification. An explicit selected document set governs incorporation. A narrow task/range request does not authorize incorporation of all feature documents or integration of unfinished work: merge only when the selected branch difference and documents are coherent within that scope; otherwise report the unmet prerequisite. Retain active sources and pending reassessment until their established requirements are satisfied.

When the applicable integration gate is met, verify working-branch acceptance, then merge with an explicit two-parent commit, verify the merged state, and push the target. **sdd-manage** coordinates this Git integration; a direct invocation follows the same protocol. Report task completion separately from branch acceptance, target integration, and published merge status. A merge failure does not erase previously verified task commits; it blocks the workflow's integrated completion. Stop after this boundary without selecting additional tasks or steering.
